### PR TITLE
Add author to pyproject.toml to appear on pypi

### PR DESCRIPTION
**Pull request by cm-demo**
This PR was sent as part of the [OSDC](https://osdc.code-maven.com/) taught by @szabgab

### CODE REVIEW

**Review by vangheem — APPROVED** [review]

**Review by vangheem — APPROVED** [review]

**Comment by vangheem** [comment]
didn't work:

```
Caused by: pyproject.toml is invalid
  Caused by: pyproject.toml is not PEP 517 compliant: invalid type: string "Nathan Van Gheem <vangheem@gmail.com>", expected a table with 'name' and 'email' keys
```

**Comment by vangheem** [comment]
assuming there might not be a human behind this PR. closing.

**Comment by szabgab** [comment]
I am not sure why did you assume that there is no human behind this PR. I'll take a look at the failure.

**Comment by vangheem** [comment]
sorry, my bad! The handle just looked odd to me.

**Comment by szabgab** [comment]
No problem. I use that account when I do demo, so I can show how is it to send a PR from an account that does not have rights on my real accounts repos. I am not exactly sure why I used that account to send you the first PR.

**Pull request closed without merging**
